function JPLData = JPLVectorTable(filename, datalines)
%IMPORTFILE Import data from a text file
%  JPLEARTHSSB2000 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  JPLVectorTable = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  JPLEarthSSB2000 = JPLVectorTable("...\JPL_Earth_SSB_2000.csv", NrLines);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-May-2024 05:39:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["T", "t", "x", "y", "z", "vx", "vy", "vz"];
opts.VariableTypes = ["double", "datetime", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 2, "InputFormat", "yyyy-MMM-dd HH:mm:ss");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.CommentStyle = "$";
% Import the data
JPLData = readtable(filename, opts);

end